### ISSUE TITLE
undefined method `configuration_list' for #<Xcodeproj::Project::Object::PBXNativeTarget:0x0000000134c74c98> (NoMethodError)

### ISSUE THREAD

**Issue by sme-shyl001** [Lightricks/Kintsugi#118]
I'm getting the following error:
```
/Library/Ruby/Gems/2.6.0/gems/kintsugi-0.7.5/lib/kintsugi/apply_change_to_project.rb:457:in `child_component': undefined method `configuration_list' for #<Xcodeproj::Project::Object::PBXNativeTarget:0x0000000134c74c98> (NoMethodError)
Did you mean?  configure_with_plist
        from /Library/Ruby/Gems/2.6.0/gems/kintsugi-0.7.5/lib/kintsugi/apply_change_to_project.rb:363:in `component_at_path'
        from /Library/Ruby/Gems/2.6.0/gems/kintsugi-0.7.5/lib/kintsugi/apply_change_to_project.rb:967:in `add_file_reference'
        from /Library/Ruby/Gems/2.6.0/gems/kintsugi-0.7.5/lib/kintsugi/apply_change_to_project.rb:654:in `add_child_to_component'
        from /Library/Ruby/Gems/2.6.0/gems/kintsugi-0.7.5/lib/kintsugi/apply_change_to_project.rb:1036:in `block in add_attributes_to_component'
        from /Library/Ruby/Gems/2.6.0/gems/kintsugi-0.7.5/lib/kintsugi/apply_change_to_project.rb:1021:in `each'
        from /Library/Ruby/Gems/2.6.0/gems/kintsugi-0.7.5/lib/kintsugi/apply_change_to_project.rb:1021:in `add_attributes_to_component'
        from /Library/Ruby/Gems/2.6.0/gems/kintsugi-0.7.5/lib/kintsugi/apply_change_to_project.rb:815:in `add_build_configuration'
        from /Library/Ruby/Gems/2.6.0/gems/kintsugi-0.7.5/lib/kintsugi/apply_change_to_project.rb:666:in `add_child_to_component'
        from /Library/Ruby/Gems/2.6.0/gems/kintsugi-0.7.5/lib/kintsugi/apply_change_to_project.rb:1039:in `block (2 levels) in add_attributes_to_component'
        from /Library/Ruby/Gems/2.6.0/gems/kintsugi-0.7.5/lib/kintsugi/apply_change_to_project.rb:1038:in `each'
        from /Library/Ruby/Gems/2.6.0/gems/kintsugi-0.7.5/lib/kintsugi/apply_change_to_project.rb:1038:in `block in add_attributes_to_component'
        from /Library/Ruby/Gems/2.6.0/gems/kintsugi-0.7.5/lib/kintsugi/apply_change_to_project.rb:1021:in `each'
        from /Library/Ruby/Gems/2.6.0/gems/kintsugi-0.7.5/lib/kintsugi/apply_change_to_project.rb:1021:in `add_attributes_to_component'
        from /Library/Ruby/Gems/2.6.0/gems/kintsugi-0.7.5/lib/kintsugi/apply_change_to_project.rb:809:in `add_build_configuration_list'
        from /Library/Ruby/Gems/2.6.0/gems/kintsugi-0.7.5/lib/kintsugi/apply_change_to_project.rb:664:in `add_child_to_component'
        from /Library/Ruby/Gems/2.6.0/gems/kintsugi-0.7.5/lib/kintsugi/apply_change_to_project.rb:1036:in `block in add_attributes_to_component'
        from /Library/Ruby/Gems/2.6.0/gems/kintsugi-0.7.5/lib/kintsugi/apply_change_to_project.rb:1021:in `each'
        from /Library/Ruby/Gems/2.6.0/gems/kintsugi-0.7.5/lib/kintsugi/apply_change_to_project.rb:1021:in `add_attributes_to_component'
        from /Library/Ruby/Gems/2.6.0/gems/kintsugi-0.7.5/lib/kintsugi/apply_change_to_project.rb:956:in `add_target'
        from /Library/Ruby/Gems/2.6.0/gems/kintsugi-0.7.5/lib/kintsugi/apply_change_to_project.rb:650:in `add_child_to_component'
        from /Library/Ruby/Gems/2.6.0/gems/kintsugi-0.7.5/lib/kintsugi/apply_change_to_project.rb:309:in `block in apply_change_to_component'
        from /Library/Ruby/Gems/2.6.0/gems/kintsugi-0.7.5/lib/kintsugi/apply_change_to_project.rb:308:in `each'
        from /Library/Ruby/Gems/2.6.0/gems/kintsugi-0.7.5/lib/kintsugi/apply_change_to_project.rb:308:in `apply_change_to_component'
        from /Library/Ruby/Gems/2.6.0/gems/kintsugi-0.7.5/lib/kintsugi/apply_change_to_project.rb:321:in `block in apply_change_to_component'
        from /Library/Ruby/Gems/2.6.0/gems/kintsugi-0.7.5/lib/kintsugi/apply_change_to_project.rb:315:in `each'
        from /Library/Ruby/Gems/2.6.0/gems/kintsugi-0.7.5/lib/kintsugi/apply_change_to_project.rb:315:in `apply_change_to_component'
        from /Library/Ruby/Gems/2.6.0/gems/kintsugi-0.7.5/lib/kintsugi/apply_change_to_project.rb:64:in `apply_change_to_project'
        from /Library/Ruby/Gems/2.6.0/gems/kintsugi-0.7.5/lib/kintsugi/merge.rb:96:in `apply_change_and_copy_to_original_path'
        from /Library/Ruby/Gems/2.6.0/gems/kintsugi-0.7.5/lib/kintsugi/merge.rb:45:in `resolve_conflicts'
        from /Library/Ruby/Gems/2.6.0/gems/kintsugi-0.7.5/lib/kintsugi/cli.rb:207:in `block in create_root_command'
        from /Library/Ruby/Gems/2.6.0/gems/kintsugi-0.7.5/lib/kintsugi.rb:26:in `run'
        from /Library/Ruby/Gems/2.6.0/gems/kintsugi-0.7.5/bin/kintsugi:10:in `<top (required)>'
        from /usr/local/bin/kintsugi:23:in `load'
        from /usr/local/bin/kintsugi:23:in `<main>'

```

**Comment by barakwei** [comment]
Can you run Kintsugi with `--changes-output-path` please?
