### ISSUE TITLE
Error when using `--changes-output-path`

### ISSUE THREAD

**Issue by oskargargas** [Lightricks/Kintsugi#20]
Hi, I wanted to preview what changes will be made. I used `--changes-output-path` option. Unfortunately it finished with an error. Regular merge (without `--changes-output-path`) worked like a charm! This tool is a lifesaver, thanks for it! :D 

```kintsugi XXX.xcodeproj/project.pbxproj --changes-output-path=$HOME/Desktop/tmp
Traceback (most recent call last):
	6: from /Users/oskar/.rvm/gems/ruby-2.7.1@iko3-ios/bin/ruby_executable_hooks:22:in `<main>'
	5: from /Users/oskar/.rvm/gems/ruby-2.7.1@iko3-ios/bin/ruby_executable_hooks:22:in `eval'
	4: from /Users/oskar/.rvm/gems/ruby-2.7.1@iko3-ios/bin/kintsugi:23:in `<main>'
	3: from /Users/oskar/.rvm/gems/ruby-2.7.1@iko3-ios/bin/kintsugi:23:in `load'
	2: from /Users/oskar/.rvm/gems/ruby-2.7.1@iko3-ios/gems/kintsugi-0.2.0/bin/kintsugi:31:in `<top (required)>'
	1: from /Users/oskar/.rvm/gems/ruby-2.7.1@iko3-ios/gems/kintsugi-0.2.0/lib/kintsugi/cli.rb:94:in `block in create_root_command'
/Users/oskar/.rvm/gems/ruby-2.7.1@iko3-ios/gems/kintsugi-0.2.0/lib/kintsugi.rb:39:in `resolve_conflicts': uninitialized constant #<Class:Kintsugi>::JSON (NameError)```

**Comment by byohay** [comment]
Totally right! I probably missed an import during a recent refactoring. Will fix it soon 👍

**Comment by byohay** [comment]
@oskargargas the fix was merged, PLMK if there are any problems still
