### ISSUE TITLE
Installing merge driver fails

### ISSUE THREAD

**Issue by igorkulman** [Lightricks/Kintsugi#32]
I have kintsugi 0.3.1 installed as a gem via rbenv, the rbenv shims folder is in my path. 

```
❯ which kintsugi
/Users/igorkulman/.rbenv/shims/kintsugi
```

Trying to run

```kintsugi install-driver```

results in

```
Traceback (most recent call last):
	5: from /Users/igorkulman/.rbenv/versions/2.7.2/bin/kintsugi:23:in `<main>'
	4: from /Users/igorkulman/.rbenv/versions/2.7.2/bin/kintsugi:23:in `load'
	3: from /Users/igorkulman/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/kintsugi-0.3.1/bin/kintsugi:31:in `<top (required)>'
	2: from /Users/igorkulman/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/kintsugi-0.3.1/lib/kintsugi/cli.rb:94:in `block in create_root_command'
	1: from /Users/igorkulman/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/kintsugi-0.3.1/lib/kintsugi.rb:32:in `resolve_conflicts'
/Users/igorkulman/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/kintsugi-0.3.1/lib/kintsugi.rb:98:in `validate_project': File '/Users/igorkulman/install-driver' doesn't exist (ArgumentError)
```

Looks like the `install-driver` command is not recognized and kintsugi considers it a project file path.

**Comment by byohay** [comment]
Hey @igorkulman! 
Sorry but we haven't made a release with the `install-driver` yet! We'll do it soon enough

**Comment by byohay** [comment]
Hi @igorkulman, I pushed a new release 0.4.0, it should work now!
