### ISSUE TITLE
undefined method `path' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by igorkulman** [Lightricks/Kintsugi#89]
I installed kintsugi via `gem install kintsugi` on a new machine, trying to merge a simple conflict I get this error

```
❯ kintsugi Redacted.xcodeproj/project.pbxproj
Traceback (most recent call last):
	30: from /Users/igorkulman/.rbenv/versions/2.7.6/bin/kintsugi:23:in `<main>'
	29: from /Users/igorkulman/.rbenv/versions/2.7.6/bin/kintsugi:23:in `load'
	28: from /Users/igorkulman/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/kintsugi-0.6.1/bin/kintsugi:10:in `<top (required)>'
	27: from /Users/igorkulman/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/kintsugi-0.6.1/lib/kintsugi.rb:26:in `run'
	26: from /Users/igorkulman/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/kintsugi-0.6.1/lib/kintsugi/cli.rb:203:in `block in create_root_command'
	25: from /Users/igorkulman/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/kintsugi-0.6.1/lib/kintsugi/merge.rb:45:in `resolve_conflicts'
	24: from /Users/igorkulman/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/kintsugi-0.6.1/lib/kintsugi/merge.rb:93:in `apply_change_and_copy_to_original_path'
	23: from /Users/igorkulman/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/kintsugi-0.6.1/lib/kintsugi/apply_change_to_project.rb:55:in `apply_change_to_project'
	22: from /Users/igorkulman/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/kintsugi-0.6.1/lib/kintsugi/apply_change_to_project.rb:249:in `apply_change_to_component'
	21: from /Users/igorkulman/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/kintsugi-0.6.1/lib/kintsugi/apply_change_to_project.rb:249:in `each'
	20: from /Users/igorkulman/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/kintsugi-0.6.1/lib/kintsugi/apply_change_to_project.rb:256:in `block in apply_change_to_component'
	19: from /Users/igorkulman/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/kintsugi-0.6.1/lib/kintsugi/apply_change_to_project.rb:249:in `apply_change_to_component'
	18: from /Users/igorkulman/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/kintsugi-0.6.1/lib/kintsugi/apply_change_to_project.rb:249:in `each'
	17: from /Users/igorkulman/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/kintsugi-0.6.1/lib/kintsugi/apply_change_to_project.rb:256:in `block in apply_change_to_component'
	16: from /Users/igorkulman/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/kintsugi-0.6.1/lib/kintsugi/apply_change_to_project.rb:249:in `apply_change_to_component'
	15: from /Users/igorkulman/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/kintsugi-0.6.1/lib/kintsugi/apply_change_to_project.rb:249:in `each'
	14: from /Users/igorkulman/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/kintsugi-0.6.1/lib/kintsugi/apply_change_to_project.rb:256:in `block in apply_change_to_component'
	13: from /Users/igorkulman/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/kintsugi-0.6.1/lib/kintsugi/apply_change_to_project.rb:249:in `apply_change_to_component'
	12: from /Users/igorkulman/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/kintsugi-0.6.1/lib/kintsugi/apply_change_to_project.rb:249:in `each'
	11: from /Users/igorkulman/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/kintsugi-0.6.1/lib/kintsugi/apply_change_to_project.rb:256:in `block in apply_change_to_component'
	10: from /Users/igorkulman/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/kintsugi-0.6.1/lib/kintsugi/apply_change_to_project.rb:249:in `apply_change_to_component'
	 9: from /Users/igorkulman/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/kintsugi-0.6.1/lib/kintsugi/apply_change_to_project.rb:249:in `each'
	 8: from /Users/igorkulman/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/kintsugi-0.6.1/lib/kintsugi/apply_change_to_project.rb:256:in `block in apply_change_to_component'
	 7: from /Users/igorkulman/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/kintsugi-0.6.1/lib/kintsugi/apply_change_to_project.rb:242:in `apply_change_to_component'
	 6: from /Users/igorkulman/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/kintsugi-0.6.1/lib/kintsugi/apply_change_to_project.rb:242:in `each'
	 5: from /Users/igorkulman/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/kintsugi-0.6.1/lib/kintsugi/apply_change_to_project.rb:243:in `block in apply_change_to_component'
	 4: from /Users/igorkulman/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/kintsugi-0.6.1/lib/kintsugi/apply_change_to_project.rb:522:in `add_child_to_component'
	 3: from /Users/igorkulman/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/kintsugi-0.6.1/lib/kintsugi/apply_change_to_project.rb:689:in `add_build_file'
	 2: from /Users/igorkulman/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/kintsugi-0.6.1/lib/kintsugi/apply_change_to_project.rb:689:in `find'
	 1: from /Users/igorkulman/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/kintsugi-0.6.1/lib/kintsugi/apply_change_to_project.rb:689:in `each'
/Users/igorkulman/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/kintsugi-0.6.1/lib/kintsugi/apply_change_to_project.rb:690:in `block in add_build_file': undefined method `path' for nil:NilClass (NoMethodError)
```
I use ruby 2.7

```
❯ ruby -v
ruby 2.7.6p219 (2022-04-12 revision c9c2245c0a) [arm64-darwin21]
```

via rbenv

**Comment by byohay** [comment]
hi @igorkulman, I was able to reproduce the problem and will submit a fix soon. Just note that it means that you have a build file without file reference in the project (it doesn't break the project, but it's redundant).
