### ISSUE TITLE
undefined method `to_tree_hash' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by tkafka** [Lightricks/Kintsugi#95]
Hello, I am getting the following error when running `kinstugi` on macOS Ventura, trying to merge a project file with conflicts:

Any idea what is wrong?

```
/opt/homebrew/lib/ruby/gems/3.1.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project/object/target_dependency.rb:83:in `to_tree_hash': undefined method `to_tree_hash' for nil:NilClass (NoMethodError)

          hash['targetProxy'] = target_proxy.to_tree_hash
                                            ^^^^^^^^^^^^^
	from /opt/homebrew/lib/ruby/gems/3.1.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project/object.rb:454:in `map'
	from /opt/homebrew/lib/ruby/gems/3.1.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project/object.rb:454:in `block in to_tree_hash'
	from /opt/homebrew/lib/ruby/gems/3.1.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project/object.rb:452:in `each'
	from /opt/homebrew/lib/ruby/gems/3.1.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project/object.rb:452:in `to_tree_hash'
	from /opt/homebrew/lib/ruby/gems/3.1.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project/object.rb:454:in `map'
	from /opt/homebrew/lib/ruby/gems/3.1.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project/object.rb:454:in `block in to_tree_hash'
	from /opt/homebrew/lib/ruby/gems/3.1.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project/object.rb:452:in `each'
	from /opt/homebrew/lib/ruby/gems/3.1.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project/object.rb:452:in `to_tree_hash'
	from /opt/homebrew/lib/ruby/gems/3.1.0/gems/xcodeproj-1.22.0/lib/xcodeproj/project.rb:328:in `to_tree_hash'
	from /opt/homebrew/lib/ruby/gems/3.1.0/gems/xcodeproj-1.22.0/lib/xcodeproj/differ.rb:65:in `project_diff'
	from /opt/homebrew/lib/ruby/gems/3.1.0/gems/kintsugi-0.6.3/lib/kintsugi/merge.rb:39:in `resolve_conflicts'
	from /opt/homebrew/lib/ruby/gems/3.1.0/gems/kintsugi-0.6.3/lib/kintsugi/cli.rb:203:in `block in create_root_command'
	from /opt/homebrew/lib/ruby/gems/3.1.0/gems/kintsugi-0.6.3/lib/kintsugi.rb:26:in `run'
	from /opt/homebrew/lib/ruby/gems/3.1.0/gems/kintsugi-0.6.3/bin/kintsugi:10:in `<top (required)>'
	from /opt/homebrew/lib/ruby/gems/3.1.0/bin/kintsugi:25:in `load'
	from /opt/homebrew/lib/ruby/gems/3.1.0/bin/kintsugi:25:in `<main>'
```

**Comment by byohay** [comment]
Hi,
Your project may have reached an invalid state - One of the targets has a target dependency on a `nil` target. Hard to tell how it arrived at such a state though.
Anyway, the code that crashes is in [xcodeproj](https://github.com/cocoapods/xcodeproj), so open an issue there if you think it's still an issue.

**Comment by samsymons** [comment]
Sorry to ping an old issue, but I ran into this today as well and found that it was an Xcode build tool plugin causing it. Running this caused a very similar stack trace:

```ruby
require 'xcodeproj'

project_path = 'SomeProjectFile.xcodeproj'
project = Xcodeproj::Project.open(project_path)

project.targets.each do |target|
  puts "#{target.name} (#{target.uuid})"

  target.dependencies.each do |dependency|
    puts "  #{dependency.to_tree_hash}" # undefined method `to_tree_hash' for nil:NilClass (NoMethodError)
  end
end
```

Removing the plugin fixed the issue for me. This is of course not related to Kintsugi directly and appears to instead be an issue with Xcodeproj, but I wanted to note this here for anyone else who stumbles across this issue.
